### ISSUE TITLE
Unable to Run floyd commands on the Command Line Interface 

### ISSUE THREAD

**Issue by djokester** [floydhub/floyd-docs#128]
On running any floyd command I receive the following error 
`>>> floyd login`

```
Traceback (most recent call last):
  File "/home/djokester/anaconda3/bin/floyd", line 4, in <module>
    import floyd.main
  File "/home/djokester/anaconda3/lib/python3.6/site-packages/floyd/main.py", line 6, in <module>
    from floyd.cli.utils import get_cli_version, is_conda_env
  File "/home/djokester/anaconda3/lib/python3.6/site-packages/floyd/cli/utils.py", line 5, in <module>
    from floyd.manager.auth_config import AuthConfigManager
  File "/home/djokester/anaconda3/lib/python3.6/site-packages/floyd/manager/auth_config.py", line 5, in <module>
    from floyd.model.access_token import AccessToken
  File "/home/djokester/anaconda3/lib/python3.6/site-packages/floyd/model/access_token.py", line 27, in <module>
    class AccessToken(BaseModel):
  File "/home/djokester/anaconda3/lib/python3.6/site-packages/floyd/model/access_token.py", line 29, in AccessToken
    schema = AccessTokenSchema(strict=True)
TypeError: __init__() got an unexpected keyword argument 'strict'

```

**Comment by MoustafaAMahmoud** [comment]
+1 
using ==>  conda install -y -c conda-forge -c floydhub floyd-cli 
ubuntu 16.04

**Comment by houqp** [comment]
Hi, this should have been fixed yesterday, could you guys give the latest version of CLI (0.10.35) a try?

**Comment by MoustafaAMahmoud** [comment]
Fixed thanks :+1:
