### ISSUE TITLE
IOError: [Errno 6] No such device or address: './.gnupg/S.gpg-agent'

### ISSUE THREAD

**Issue by somyars1** [floydhub/floyd-docs#45]
floyd run --gpu --env tensorflow "python mnist_cnn.py"
Traceback (most recent call last):
  File "/home/somya/anaconda2/bin/floyd", line 11, in <module>
    sys.exit(cli())
  File "/home/somya/anaconda2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/somya/anaconda2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/somya/anaconda2/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/somya/anaconda2/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/somya/anaconda2/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/somya/anaconda2/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/somya/anaconda2/lib/python2.7/site-packages/floyd/cli/run.py", line 114, in run
    module_id = ModuleClient().create(module)
  File "/home/somya/anaconda2/lib/python2.7/site-packages/floyd/client/module.py", line 34, in create
    upload_files, total_file_size = get_files_in_current_directory(file_type='code')
  File "/home/somya/anaconda2/lib/python2.7/site-packages/floyd/client/files.py", line 80, in get_files_in_current_directory
    local_files.append((file_type, (unix_style_path(file_path), open(file_path, 'rb'), 'text/plain')))
IOError: [Errno 6] No such device or address: './.gnupg/S.gpg-agent'

I tried following the steps in the quick start page to run the mnist_cnn.py and ran into this error. Can anyone help? Thanks

**Comment by houqp** [comment]
Does this happen every time you run the command? Could you confirm that you have a directory named `./.gnupg/` inside the directory where you ran the command?

**Comment by somyars1** [comment]
Thanks @houqp . I ran the command again twice and its working fine though I am unsure as to what might the reason for that initial error. I was running the command inside the quick-start project directory and it doesn't have any directory named ./.gnupg/.

**Comment by houqp** [comment]
Thanks for the update. My guess is it has something to do with `./.gnupg/S.gpg-agent` getting created temporarily and then got deleted afterwards while floyd-cli is uploading the directory. If you managed to be able to reproduce the error reliably, feel free to reopen this issue.
